name: Canary Release

on:
  push:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish-canary:
    name: Publish Canary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: ^7.9.5

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Release Canary
        id: canary
        uses: 'kamilkisiela/release-canary@master'
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          npm-script: 'pnpm release:canary'
          changesets: true
