name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:

env:
  MNEMONIC: ${{ secrets.MNEMONIC }}

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - name: Setup Node v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Setup NPM credentials
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Type Check
        run: pnpm tsc
      - name: Run tests
        run: pnpm test
