name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:

env:
  MNEMONIC: ${{ secrets.MNEMONIC }}

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - name: Setup Node v18
        uses: actions/setup-node@v3
        with:
          node-version: '^18.7.0'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Codegen
        run: pnpm codegen
      - name: Build
        run: pnpm build
      - name: Type Check
        run: pnpm tsc
      - name: Run tests
        run: pnpm test
