name: Deploy Subgraph

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        default: 'production'
        options:
          - preview
          - staging
          - production
      commitId:
        required: false
        description: 'Commit ID'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Subgraph Deploy Runner
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.commitId }}

      - name: Setup Node v18
        uses: actions/setup-node@v3
        with:
          node-version: '^18.7.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Codegen
        working-directory: packages/subgraph
        run: pnpm run codegen

      - name: Build
        working-directory: packages/subgraph
        run: pnpm run build

      - name: Deploy
        working-directory: packages/subgraph
        run: pnpm run deploy:${{ github.event.inputs.environment }}
        env:
          DEPLOY_KEY: '${{ secrets.DEPLOY_KEY }}'
